// Это содержимое файла build.gradle в КОРНЕ проекта
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Указываем версию плагина Android Gradle
        classpath 'com.android.tools.build:gradle:7.4.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}