buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Обновляем версию плагина для поддержки API 35
        classpath 'com.android.tools.build:gradle:8.5.1'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
